#version: '3.9'
services:
  keijiban-back:
    container_name: keijiban-back
    build: backend
    ports:
      - 8123:8123  # ホストマシンのポート8000を、docker内のポート8000に接続する
  mysql:
    image: mysql:9.2.0
    container_name: keijiban-sql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "sample"
      TZ: "Asia/Tokyo"
